replicaCount: 1

image:
  repository: ghcr.io/netsoc/lxd8s
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ''

nameOverride: ''
fullnameOverride: ''

podAnnotations: {}
nodeSelector: {}
tolerations: []
affinity: {}

service:
  type: ClusterIP
  port: 443
ingressRoute:
  enabled: false
  hosts: []

startupProbe:
  initialDelaySeconds: 5
  timeoutSeconds: 5
  periodSeconds: 3
  failureThreshold: 100
livenessProbe:
  timeoutSeconds: 5
  periodSeconds: 10
terminationGracePeriodSeconds: 60

clusterDomain: cluster.local
certCount: 1
certs:
  duration: 87600h # 10 years
  renewBefore: 360h # 15 days
  key:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  subject:
    countries: [IE]
ca:
  key: ''
  cert: ''

resources:
  limits:
    hostdev.k8s.io/dev_kvm: 1
    cpu: 4000m
    memory: 3Gi
  requests:
    cpu: 4000m
    memory: 2Gi
vm:
  cpus: 4
  memory: 2048
firectlTimeout: 30000

storageClass: ''
pvc:
  lxd:
    size: 8Gi
    imgOnFilesystem: false
  storage:
    size: 64Gi
    imgOnFilesystem: false

kubelan:
  image:
    repository: ghcr.io/devplayer0/kubelan
    pullPolicy: IfNotPresent
    tag: v0.2.0
  log_level: DEBUG
  extraServices: []
  vxlan:
    interface: lxd-overlay
    vni: 7331
  hooks: {}

nat:
  host: 192.168.69.1/30
  vm: 192.168.69.2/30
network: '172.24.0.0/16'

preseed:
  config:
    images.auto_update_cached: true
    images.auto_update_interval: 6
    images.remote_cache_expiry: 0
  profiles:
    - name: default
      config:
        boot.autostart: 'false'
        limits.cpu: '1'
        limits.memory: '256MiB'
        security.nesting: 'true'
      devices:
        root:
          size: 8GiB
